export { default as GetStarted } from "./GetStarted";
export { default as Dashboard } from "./Dashboard";
export { default as Profile } from "./Profile";
export { default as Games } from "./Games";
export { default as Learn } from "./Learn";
export { default as NotFound } from "./NotFound";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Language } from "./Language"
